// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SlotMachineDomain;
using System;

namespace SlotMachineDomain.Migrations
{
    [DbContext(typeof(SlotMachineContext))]
    partial class SlotMachineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SlotMachineDomain.BetRecord", b =>
                {
                    b.Property<string>("PlayerId");

                    b.Property<double>("Balance");

                    b.Property<double>("BetAmount");

                    b.Property<int>("NumRows");

                    b.Property<DateTime>("Timestamp");

                    b.Property<double>("WinAmount");

                    b.HasKey("PlayerId");

                    b.ToTable("BetRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
